name: Cancel workflow
on: 
  workflow_call:
    inputs:
      worflow_id:
        required: true
        type: string
jobs:
  cancel:
    name: 'Cancel workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: ${{ inputs.worflow_id }}
          access_token: ${{ github.token }}