run-name: ${{ github.actor }} is checking if tag accepted
name: accept tag
on:
  push:
   branches :
    - '*'
  workflow_dispatch:
jobs:

  # Checking commit
  check_commit:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
        reviewer:  ${{ steps.commit_hook.outputs.message }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: shogo82148/actions-setup-perl@v1
        with:
            perl-version: '5.34' 
      - run: git show $GITHUB_SHA
      - name: run enviroment variables
        run : ./commit_exam.pl $GITHUB_SHA 
      - id: commit_hook
        name: setting enviroment variables
        run : ./commit_exam.pl $GITHUB_SHA >> $GITHUB_OUTPUT

  test:
    # Testing
    needs: check_commit 
    uses: agile-visualizer-team/visualizer-asp/.github/workflows/tests.yml@master

  