run-name: Pull request in a reusable way
name: Create a pull request CI/CD reusable
on:
  # push:
  #  branches :
  #   - '*'
  #   - '!master'
  #   - '!main'
  workflow_dispatch:
jobs:

  # Checking commit
  check_commit:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
        status: ${{ steps.commit_hook.conclusion }}
        testaa: "CIAO"
    steps:
      - name: check branch
        run: echo "${GITHUB_REF##*/}"
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: shogo82148/actions-setup-perl@v1
        with:
            perl-version: '5.34'
      - name: check commit
        run : git show $GITHUB_SHA
      - name: run script
        run : ./commit_hook.pl $GITHUB_SHA
      - id: commit_hook
        name: setting enviroment variables
        run : ./commit_hook.pl $GITHUB_SHA >> $GITHUB_ENV


  # Testing
  tests:
    needs: check_commit
    if:  ${{ needs.check_commit.outputs.status == 'success' }}
    uses: agile-visualizer-team/visualizer-asp/.github/workflows/tests.yml@master


  # Creating a pull request
  create_pull_request:
    needs: [tests, check_commit]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: echo " ${{ needs.check_commit.outputs.status == 'success' }} "
      # - if: ${{ env.pull_request_commit == 'true' }}
      #   run: | 
      #     run: npm ci
      #     run: npm test
      # - if: ${{ env.pull_request_commit == 'true' }}
      #   name: create pull_request
      #   uses: devops-infra/action-pull-request@v0.5.3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     target_branch: master
      #     title: ${{ env.title }}
      #     body: ${{ env.body }}
      #     reviewer: ${{ env.reviewer }}
